/**
 * Device-id identity helpers (client-safe).
 *
 * UNSW Quest v1 doesn't use Supabase Auth. A per-browser UUID is generated by
 * the proxy/middleware and persisted in the `quest_device_id` cookie. Both
 * client and server components read it to identify the current player and
 * pass it into `quest_*` RPCs as `p_user_id`.
 *
 * This file is safe to import from browser code. Server components should
 * import `getDeviceIdServer` from `./device-id.server` instead — that file
 * pulls in `next/headers`, which can't be bundled for the client.
 */

export const COOKIE_NAME = "quest_device_id";

/**
 * Read the `quest_device_id` cookie from a browser context. Throws if the
 * cookie is missing (which shouldn't happen — proxy.ts sets it on the
 * first request).
 */
export function getDeviceIdClient(): string {
  if (typeof document === "undefined") {
    throw new Error(
      "[device-id] getDeviceIdClient() called outside the browser. " +
        "Use getDeviceIdServer() from './device-id.server' in server components.",
    );
  }
  const prefix = `${COOKIE_NAME}=`;
  const match = document.cookie
    .split(";")
    .map((c) => c.trim())
    .find((c) => c.startsWith(prefix));
  if (!match) {
    throw new Error(
      `[device-id] Missing ${COOKIE_NAME} cookie in document.cookie. ` +
        `proxy.ts should have set this on the page load that delivered this script.`,
    );
  }
  return decodeURIComponent(match.slice(prefix.length));
}
