// Generated by Supabase MCP — do not edit by hand.
// Regenerate after schema changes via the Supabase CLI or MCP.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      quest_clue_progress: {
        Row: {
          clue_id: string;
          hints_used: number;
          hunt_session_id: string;
          id: string;
          manual_override: boolean;
          maps_used: number;
          photo_capture_url: string | null;
          unlocked_at: string;
        };
        Insert: {
          clue_id: string;
          hints_used?: number;
          hunt_session_id: string;
          id?: string;
          manual_override?: boolean;
          maps_used?: number;
          photo_capture_url?: string | null;
          unlocked_at?: string;
        };
        Update: {
          clue_id?: string;
          hints_used?: number;
          hunt_session_id?: string;
          id?: string;
          manual_override?: boolean;
          maps_used?: number;
          photo_capture_url?: string | null;
          unlocked_at?: string;
        };
        Relationships: [];
      };
      quest_clues: {
        Row: {
          body_text: string;
          geofence_radius_m: number;
          hints: Json;
          hunt_id: string;
          id: string;
          image_url: string | null;
          location_lat: number | null;
          location_lng: number | null;
          location_name: string | null;
          photo_challenge_prompt: string | null;
          qr_code_payload: string | null;
          sequence_in_tier: number;
          tier: number;
          type: string;
          verification_type: string;
        };
        Insert: {
          body_text: string;
          geofence_radius_m?: number;
          hints?: Json;
          hunt_id: string;
          id?: string;
          image_url?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          location_name?: string | null;
          photo_challenge_prompt?: string | null;
          qr_code_payload?: string | null;
          sequence_in_tier: number;
          tier: number;
          type?: string;
          verification_type?: string;
        };
        Update: {
          body_text?: string;
          geofence_radius_m?: number;
          hints?: Json;
          hunt_id?: string;
          id?: string;
          image_url?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          location_name?: string | null;
          photo_challenge_prompt?: string | null;
          qr_code_payload?: string | null;
          sequence_in_tier?: number;
          tier?: number;
          type?: string;
          verification_type?: string;
        };
        Relationships: [];
      };
      quest_hunt_sessions: {
        Row: {
          completed_at: string | null;
          created_at: string;
          current_sequence: number;
          current_tier: number;
          hint_penalty_seconds: number;
          hunt_id: string;
          id: string;
          started_at: string | null;
          state: string;
          team_id: string;
          total_time_seconds: number | null;
        };
        Insert: {
          completed_at?: string | null;
          created_at?: string;
          current_sequence?: number;
          current_tier?: number;
          hint_penalty_seconds?: number;
          hunt_id: string;
          id?: string;
          started_at?: string | null;
          state?: string;
          team_id: string;
          total_time_seconds?: number | null;
        };
        Update: {
          completed_at?: string | null;
          created_at?: string;
          current_sequence?: number;
          current_tier?: number;
          hint_penalty_seconds?: number;
          hunt_id?: string;
          id?: string;
          started_at?: string | null;
          state?: string;
          team_id?: string;
          total_time_seconds?: number | null;
        };
        Relationships: [];
      };
      quest_hunts: {
        Row: {
          created_at: string;
          description: string | null;
          duration_minutes: number | null;
          hero_emoji: string | null;
          id: string;
          name: string;
          recommended_team_size: string | null;
          slug: string;
          status: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          duration_minutes?: number | null;
          hero_emoji?: string | null;
          id?: string;
          name: string;
          recommended_team_size?: string | null;
          slug: string;
          status?: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          duration_minutes?: number | null;
          hero_emoji?: string | null;
          id?: string;
          name?: string;
          recommended_team_size?: string | null;
          slug?: string;
          status?: string;
        };
        Relationships: [];
      };
      quest_profiles: {
        Row: {
          avatar_color: string;
          created_at: string;
          display_name: string;
          unsw_verified: boolean;
          user_id: string;
        };
        Insert: {
          avatar_color?: string;
          created_at?: string;
          display_name: string;
          unsw_verified?: boolean;
          user_id: string;
        };
        Update: {
          avatar_color?: string;
          created_at?: string;
          display_name?: string;
          unsw_verified?: boolean;
          user_id?: string;
        };
        Relationships: [];
      };
      quest_team_members: {
        Row: {
          joined_at: string;
          team_id: string;
          user_id: string;
        };
        Insert: {
          joined_at?: string;
          team_id: string;
          user_id: string;
        };
        Update: {
          joined_at?: string;
          team_id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      quest_teams: {
        Row: {
          created_at: string;
          hunt_id: string;
          id: string;
          invite_code: string;
          leader_user_id: string;
          name: string;
        };
        Insert: {
          created_at?: string;
          hunt_id: string;
          id?: string;
          invite_code: string;
          leader_user_id: string;
          name: string;
        };
        Update: {
          created_at?: string;
          hunt_id?: string;
          id?: string;
          invite_code?: string;
          leader_user_id?: string;
          name?: string;
        };
        Relationships: [];
      };
      mvp_games: {
        Row: {
          hardcoded_start_location: string;
          hunt_id: string;
          id: string;
          started_at: string;
          status: string;
        };
        Insert: {
          hardcoded_start_location?: string;
          hunt_id: string;
          id?: string;
          started_at?: string;
          status?: string;
        };
        Update: {
          hardcoded_start_location?: string;
          hunt_id?: string;
          id?: string;
          started_at?: string;
          status?: string;
        };
        Relationships: [];
      };
      mvp_hunts: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          name: string;
          status: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          name: string;
          status?: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          name?: string;
          status?: string;
        };
        Relationships: [];
      };
      mvp_players: {
        Row: {
          awaiting_walk_ack: boolean;
          completed_at: string | null;
          created_at: string;
          game_id: string;
          id: string;
          joined_at: string;
          name: string;
          started_at: string | null;
          total_time_seconds: number | null;
        };
        Insert: {
          awaiting_walk_ack?: boolean;
          completed_at?: string | null;
          created_at?: string;
          game_id: string;
          id?: string;
          joined_at?: string;
          name: string;
          started_at?: string | null;
          total_time_seconds?: number | null;
        };
        Update: {
          awaiting_walk_ack?: boolean;
          completed_at?: string | null;
          created_at?: string;
          game_id?: string;
          id?: string;
          joined_at?: string;
          name?: string;
          started_at?: string | null;
          total_time_seconds?: number | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      quest_create_team: {
        Args: { p_hunt_id: string; p_team_name?: string };
        Returns: { invite_code: string; session_id: string; team_id: string }[];
      };
      quest_ensure_profile: {
        Args: { p_display_name: string };
        Returns: {
          avatar_color: string;
          created_at: string;
          display_name: string;
          unsw_verified: boolean;
          user_id: string;
        };
      };
      quest_join_team: {
        Args: { p_invite_code: string };
        Returns: { hunt_id: string; team_id: string }[];
      };
      quest_apply_penalty: {
        Args: {
          p_seconds: number;
          p_session_id: string;
        };
        Returns: Database["public"]["Tables"]["quest_hunt_sessions"]["Row"];
      };
      quest_start_hunt: {
        Args: { p_team_id: string };
        Returns: Database["public"]["Tables"]["quest_hunt_sessions"]["Row"];
      };
      quest_unlock_clue: {
        Args: {
          p_clue_id: string;
          p_hints_used?: number;
          p_manual_override?: boolean;
          p_maps_used?: number;
          p_photo_url?: string;
          p_session_id: string;
        };
        Returns: Database["public"]["Tables"]["quest_hunt_sessions"]["Row"];
      };
      mvp_join_game: {
        Args: {
          p_game_id: string;
          p_name: string;
          p_existing_player_id?: string | null;
        };
        Returns: Json;
      };
      mvp_get_player_state: {
        Args: { p_player_id: string };
        Returns: Json;
      };
      mvp_confirm_start: {
        Args: { p_player_id: string };
        Returns: Json;
      };
      mvp_ack_walk: {
        Args: { p_player_id: string };
        Returns: Json;
      };
      mvp_submit_anagram: {
        Args: {
          p_player_id: string;
          p_puzzle_id: string;
          p_input: string;
        };
        Returns: Json;
      };
      mvp_submit_geocache_code: {
        Args: {
          p_player_id: string;
          p_puzzle_id: string;
          p_code: string;
        };
        Returns: Json;
      };
      mvp_record_photo: {
        Args: {
          p_player_id: string;
          p_puzzle_id: string;
          p_photo_url?: string | null;
          p_skipped?: boolean;
        };
        Returns: Json;
      };
      mvp_complete_player: {
        Args: { p_player_id: string };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type Inserts<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type Updates<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
